linux/pingest4: Fix ShellCheck error.

diff --git a/bin/linux/pingest4 b/bin/linux/pingest4
--- a/bin/linux/pingest4
+++ b/bin/linux/pingest4
@@ -9,13 +9,13 @@ IFS=$(printf ' \t\n_'); IFS=${IFS%_}
 PATH=/bin:/sbin:/usr/bin:/usr/sbin
 export IFS LC_ALL=C LANG=C PATH
 
-readonly progname=${0##*/}
-readonly version=2.1.1.20191128
+readonly progname="${0##*/}"
+readonly version=2.1.2.20220710
 
 # usage <exit-code>
 usage() {
     echo "usage: $progname [-hv] [-o output]" 1>&2
-    exit $1
+    exit "$1"
 }
 
 # version (no parameter)
@@ -43,11 +43,10 @@ while getopts 'ho:v' opt; do
     \?)     usage 1 ;;
     esac
 done
-shift $(($OPTIND - 1))
+shift $((OPTIND - 1))
 
-if [ -n "$output" -a "$output" != - ]; then
-    { exec >"$output"; } 2>/dev/null
-    [ $? -eq 0 ] || error "$output: cannot open"
+if [ -n "$output" ] && [ "$output" != - ]; then
+    { exec >"$output"; } 2>/dev/null || error "$output: cannot open"
 fi
 
 readonly addrbase=192.168.24.
@@ -66,13 +65,12 @@ readonly sortcmd='sort -V'
 
 # do_ping <IP address>
 do_ping() {
-    $pingcmd $1 >/dev/null
-    [ $? -eq 0 ] && echo $1
+    $pingcmd "$1" >/dev/null && echo "$1"
 }
 
 {
     for i in $(seq 1 254); do
-        do_ping $addrbase$i &
+        do_ping "$addrbase$i" &
     done
     wait
 } | $sortcmd
